spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merukari
    username: postgres
    password: postgres
    
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 25
    username: test.example.com
    properties:
      mail:
        smtp:
          auth: true
#          starttls:
#            enable: true

server:
  servlet:
    context-path: /merukari

#mybatis設定
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/config/mybatis.xml
  check-config-location: true

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          mapper:
            ItemMapper: DEBUG
            CategoryMapper: DEBUG
            MemberMapper: DEBUG