spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merukari
    username: postgres
    password: postgres
    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: side19river951happy128@gmail.com
    password: oyeylaxwskzzdguz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /merukari

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/config/mybatis.xml
  check-config-location: true

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          mapper:
            ItemMapper: DEBUG
            CategoryMapper: DEBUG